
package com.demo.practice.test;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Test15", targetNamespace = "http://springboot.demo.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Test15 {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "test01", targetNamespace = "http://springboot.demo.com/", className = "com.demo.springboot.Test01")
    @ResponseWrapper(localName = "test01Response", targetNamespace = "http://springboot.demo.com/", className = "com.demo.springboot.Test01Response")
    @Action(input = "http://springboot.demo.com/Test15/test01Request", output = "http://springboot.demo.com/Test15/test01Response")
    public String test01();

}
