
package com.demo.practice.test;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Test15Service", targetNamespace = "http://springboot.demo.com/", wsdlLocation = "http://localhost:8080/test?wsdl")
public class Test15Service
    extends Service
{

    private final static URL TEST15SERVICE_WSDL_LOCATION;
    private final static WebServiceException TEST15SERVICE_EXCEPTION;
    private final static QName TEST15SERVICE_QNAME = new QName("http://springboot.demo.com/", "Test15Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/test?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TEST15SERVICE_WSDL_LOCATION = url;
        TEST15SERVICE_EXCEPTION = e;
    }

    public Test15Service() {
        super(__getWsdlLocation(), TEST15SERVICE_QNAME);
    }

    public Test15Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), TEST15SERVICE_QNAME, features);
    }

    public Test15Service(URL wsdlLocation) {
        super(wsdlLocation, TEST15SERVICE_QNAME);
    }

    public Test15Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TEST15SERVICE_QNAME, features);
    }

    public Test15Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Test15Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Test15
     */
    @WebEndpoint(name = "Test15Port")
    public Test15 getTest15Port() {
        return super.getPort(new QName("http://springboot.demo.com/", "Test15Port"), Test15.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Test15
     */
    @WebEndpoint(name = "Test15Port")
    public Test15 getTest15Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://springboot.demo.com/", "Test15Port"), Test15.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TEST15SERVICE_EXCEPTION!= null) {
            throw TEST15SERVICE_EXCEPTION;
        }
        return TEST15SERVICE_WSDL_LOCATION;
    }

}
